### ISSUE TITLE
[Request] Request feedback for API creation

### ISSUE THREAD

**Issue by ZinnaChoi** [JoshRyu/logistics#13]
Hello, @JoshRyu 

I have completed the basic CRUD operations and are ready to proceed to the next step. 
Currently, we have individual CRUD operations for store and product, but we lack a logic for registering products in a store. 

I'm considering implementing the following APIs for this purpose:

**1. POST: Register a Product in a Store (Single Entry)**
- This will add a new row to the store_product table.

**2. POST: Register Products in a Store (Excel Upload)**
- Since each store needs to register its products individually, and considering the number of stores multiplied by the number of products per store, it seems necessary to have an Excel upload feature for product registration.

**3. GET: Retrieve a List of Products Registered in a Store for a Specific Month (With Pagination)**
- Input: store_code, month
- Output: Display the product name and the price of the product in the store (either discounted or not, referring to the discount table).

These are the three APIs I've thought of so far. What do you think?

![image](https://github.com/JoshRyu/logistics/assets/142554606/12a915bc-755e-4952-9607-2bc071a2af6a)

**Comment by JoshRyu** [comment]
Thanks for creating issues for logistics project.
**1. POST: Register a Product in a Store (Single Entry)**
-  Sounds good to me
 
**2. POST: Register Products in a Store (Excel Upload)**
- I think the webpage should have excel download func for providing the example excel file for the upload.
- can you provide example excel sheets so that we can figure out possible duplication etc?

**3. GET: Retrieve a List of Products Registered in a Store for a Specific Month (With Pagination)**
- if there is a product store have already registered but need a discount, do we have to register a new product?
- what if there is discount for a product A and at the same month discount is canceled, what happen next?
- if there is a product that the user registered on previous month, what happens to this product in the next month? is it deleted? or kept in a same month? (in this case it wouldn't be possible to query this because it is registered previous month)
  - what's expected user behaviour you think in this scenario?

**Comment by ZinnaChoi** [comment]
@JoshRyu 

After this [PR](https://github.com/JoshRyu/logistics/pull/14) is merged, we can close this issue! : )
